spring.application.name=demo
server.port=8080
spring.mongodb.uri=mongodb+srv://admin:jaja121605@cluster0.v2ie0ej.mongodb.net/?appName=Cluster0
spring.mongodb.database=place
# spring.data.mongodb.uri=mongodb+srv://admin:Jaja121605@cluster0.jwrwgeo.mongodb.net/Sights?retryWrites=true&w=majority